### ISSUE TITLE
Videresend bekræftelseskode til automatisk videresendelse

### ISSUE THREAD

**Issue by sorenlyhne** [askehansen/dinero-forward#1]
Hej Aske,

Tak for et overmåde nyttigt værktøj. Jeg har en drøm om at kunne automatisere bogføringen yderligere, og i den forbindelse vil det være nyttigt at kunne opsætte automatisk videresendelse af fakturaer til dinero-forward. I mit tilfælde har jeg forsøgt med gmail, men det kræver, at man har den kode, der tilsendes email-adressen, man vil videresende til (= min personlige dinero-forward-adresse). 

Er det muligt, at dinero-forward kan genkende sådanne bekræftelsesmails og videresende dem til min egen mail?

Vh Søren Lyhne

**Comment by askehansen** [comment]
Hej Søren, jeg arbejder på en betalt løsning hvor dette er muligt

**Comment by askehansen** [comment]
Hej @sorenlyhne, dette er nu muligt og du kan logge ind og tilkøbe det her https://www.dinero-forward.dk/user_sessions/new

Lad mig høre hvis du har nogle spørgsmål til det 🙂
