### ISSUE TITLE
Understøt emails hvor fakturaen er selve emailen

### ISSUE THREAD

**Issue by stephenson** [askehansen/dinero-forward#2]
Hej Ask
Super produkt, tak for det!

Vi får en del fakturaer hvor selve body på emailen er selve fakturaen, det kunne være super hvis dinero-forward i tilfælde af ingen pdf vedhæftede lavede indholdet af emailen om til en PDF og sende den til Dinero.

**Comment by askehansen** [comment]
Hej Niklas, jeg er helt enig :) Du er meget velkommen til at lave et pull request.

**Comment by stephenson** [comment]
Ville gerne rode med et pull, meen tror readme filen kræver lidt arbejde for at gøre det let for eksterne at lave pulls :)

**Comment by mikker** [comment]
Hvor(dan) er sitet hostet? Afhængigt af hvor nemt det er at få [wkhtmltopdf](https://wkhtmltopdf.org) installeret kunne det være _nemt nok_ at gøre med [pdfkit](https://github.com/pdfkit/pdfkit)?

Jeg laver gerne et PR. Forrygende projekt og jeg vil gerne give igen 😊

**Comment by askehansen** [comment]
Hej @mikker, Tak for din interesse og jeg beklager det sene svar!
Jeg har faktisk lavet dette som ligger i en branch sammen med et par andre opdateringer som snart bliver en del af en betalt version af dinero forward :)

For at svare på dit spørgsmål så er det hosted på Heroku og benytter Postgres, Redis, Sendgrid og S3.

**Comment by askehansen** [comment]
Hej @mikker og @stephenson. Dette er nu muligt ved at logge ind her og opgradere: https://www.dinero-forward.dk/user_sessions/new

Lad mig høre hvis i har nogle spørgsmål til det 🙂
